version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      backend:
    restart: always
    tty: true

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    entrypoint: >
      /bin/bash -c "
        rabbitmq-server &
        sleep 10 && rabbitmq-plugins enable rabbitmq_web_stomp &
        tail -f /dev/null
      "
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  backend: